<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('countries', function (Blueprint $table) {
            $table->id();
            $table->string('name');
            $table->string('code');
            $table->timestamps();
            $table->softDeletes();
        });

        DB::table('countries')->insert(array(
            [
                "id" => 1,
                "code" => "AF",
                "name" => "أفغانستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ],
            array(
                "id" => 2,
                "code" => "AX",
                "name" => "اسلاند",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 3,
                "code" => "AL",
                "name" => "ألبانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 4,
                "code" => "DZ",
                "name" => "الجزائر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 5,
                "code" => "AS",
                "name" => "جزر ساموا الأمريكية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 6,
                "code" => "AD",
                "name" => "أندورا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 7,
                "code" => "AO",
                "name" => "أنغولا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 8,
                "code" => "AI",
                "name" => "أنغويلا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 9,
                "code" => "AQ",
                "name" => "أنتاركتيكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 10,
                "code" => "AG",
                "name" => "أنتيغوا وبربودا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 11,
                "code" => "AR",
                "name" => "الأرجنتين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 12,
                "code" => "AM",
                "name" => "أرمينيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 13,
                "code" => "AW",
                "name" => "أروبا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 14,
                "code" => "AU",
                "name" => "أستراليا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 15,
                "code" => "AT",
                "name" => "النمسا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 16,
                "code" => "AZ",
                "name" => "أذربيجان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 17,
                "code" => "BS",
                "name" => "جزر البهاما",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 18,
                "code" => "BH",
                "name" => "مملكة البحرين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 19,
                "code" => "BD",
                "name" => "بنجلاديش",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 20,
                "code" => "BB",
                "name" => "باربادوس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 21,
                "code" => "BY",
                "name" => "بيلاروس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 22,
                "code" => "BE",
                "name" => "بلجيكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 23,
                "code" => "BZ",
                "name" => "بيليز",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 24,
                "code" => "BJ",
                "name" => "بنين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 25,
                "code" => "BM",
                "name" => "برمودا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 26,
                "code" => "BT",
                "name" => "بوتان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 27,
                "code" => "BO",
                "name" => "بوليفيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 28,
                "code" => "BQ",
                "name" => "بونير وسينت أوستاتيوس وسابا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 29,
                "code" => "BA",
                "name" => "البوسنة والهرسك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 30,
                "code" => "BW",
                "name" => "بوتسوانا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 31,
                "code" => "BV",
                "name" => "جزيرة بوفيه",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 32,
                "code" => "BR",
                "name" => "البرازيل",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 33,
                "code" => "IO",
                "name" => "إقليم المحيط الهندي البريطاني",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 34,
                "code" => "BN",
                "name" => "بروناي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 35,
                "code" => "BG",
                "name" => "بلغاريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 36,
                "code" => "BF",
                "name" => "بوركينا فاسو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 37,
                "code" => "BI",
                "name" => "بوروندي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 38,
                "code" => "KH",
                "name" => "كامبوديا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 39,
                "code" => "CM",
                "name" => "الكاميرون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 40,
                "code" => "CA",
                "name" => "كندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 41,
                "code" => "CV",
                "name" => "الرأس الأخضر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 42,
                "code" => "KY",
                "name" => "جزر كايمان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 43,
                "code" => "CF",
                "name" => "جمهورية أفريقيا الوسطى",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 44,
                "code" => "TD",
                "name" => "تشاد",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 45,
                "code" => "CL",
                "name" => "تشيلي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 46,
                "code" => "CN",
                "name" => "الصين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 47,
                "code" => "CX",
                "name" => "جزيرة الكريسماس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 48,
                "code" => "CC",
                "name" => "جزر الكوكوس (كيلين)",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 49,
                "code" => "CO",
                "name" => "كولومبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 50,
                "code" => "KM",
                "name" => "جزر القمر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 51,
                "code" => "CG",
                "name" => "الكونغو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 52,
                "code" => "CD",
                "name" => "الكونغو (جمهورية الكونغو الديمقراطية)",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 53,
                "code" => "CK",
                "name" => "جزر كوك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 54,
                "code" => "CR",
                "name" => "كوستاريكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 55,
                "code" => "CI",
                "name" => "كوت ديفوار (ساحل العاج)",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 56,
                "code" => "HR",
                "name" => "كرواتيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 57,
                "code" => "CU",
                "name" => "كوبا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 58,
                "code" => "CW",
                "name" => "كوراساو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 59,
                "code" => "CY",
                "name" => "قبرص",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 60,
                "code" => "CZ",
                "name" => "جمهورية التشيك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 61,
                "code" => "DK",
                "name" => "الدانمارك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 62,
                "code" => "DJ",
                "name" => "جيبوتي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 63,
                "code" => "DM",
                "name" => "دومينيكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 64,
                "code" => "DO",
                "name" => "جمهورية الدومينيكان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 65,
                "code" => "EC",
                "name" => "إكوادور",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 66,
                "code" => "EG",
                "name" => "مصر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 67,
                "code" => "SV",
                "name" => "السلفادور",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 68,
                "code" => "GQ",
                "name" => "غينيا الاستوائية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 69,
                "code" => "ER",
                "name" => "إريتريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 70,
                "code" => "EE",
                "name" => "إستونيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 71,
                "code" => "ET",
                "name" => "إثيوبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 72,
                "code" => "FK",
                "name" => "جزر فوكلاند (أيزلاس مالفيناس)",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 73,
                "code" => "FO",
                "name" => "جزر فايرو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 74,
                "code" => "FJ",
                "name" => "جزر فيجي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 75,
                "code" => "FI",
                "name" => "فنلندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 76,
                "code" => "FR",
                "name" => "فرنسا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 77,
                "code" => "GF",
                "name" => "جيانا الفرنسية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 78,
                "code" => "PF",
                "name" => "بولينزيا الفرنسية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 79,
                "code" => "TF",
                "name" => "المناطق الفرنسية الجنوبية ومناطق انتراكتيكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 80,
                "code" => "GA",
                "name" => "الجابون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 81,
                "code" => "GM",
                "name" => "جامبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 82,
                "code" => "GE",
                "name" => "جورجيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 83,
                "code" => "DE",
                "name" => "ألمانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 84,
                "code" => "GH",
                "name" => "غانا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 85,
                "code" => "GI",
                "name" => "جبل طارق",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 86,
                "code" => "GR",
                "name" => "اليونان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 87,
                "code" => "GL",
                "name" => "جرينلاند",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 88,
                "code" => "GD",
                "name" => "غرينادا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 89,
                "code" => "GP",
                "name" => "جواديلوب",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 90,
                "code" => "GU",
                "name" => "جوام",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 91,
                "code" => "GT",
                "name" => "جواتيمالا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 92,
                "code" => "GG",
                "name" => "جيرنزي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 93,
                "code" => "GN",
                "name" => "غينيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 94,
                "code" => "GW",
                "name" => "غينيا بيساو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 95,
                "code" => "GY",
                "name" => "جيانا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 96,
                "code" => "HT",
                "name" => "هايتي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 97,
                "code" => "HM",
                "name" => "جزيرة هيرد وجزر ماكدونالد",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 98,
                "code" => "VA",
                "name" => "دولة الفاتيكان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 99,
                "code" => "HN",
                "name" => "هندوراس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 100,
                "code" => "HK",
                "name" => "هونغ كونغ",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 101,
                "code" => "HU",
                "name" => "المجر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 102,
                "code" => "IS",
                "name" => "أيسلندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 103,
                "code" => "IN",
                "name" => "الهند",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 104,
                "code" => "ID",
                "name" => "إندونيسيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 106,
                "code" => "IQ",
                "name" => "العراق",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 107,
                "code" => "IE",
                "name" => "أيرلندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 108,
                "code" => "IM",
                "name" => "جزيرة مان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 110,
                "code" => "IT",
                "name" => "إيطاليا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 111,
                "code" => "JM",
                "name" => "جامايكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 112,
                "code" => "JP",
                "name" => "اليابان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 113,
                "code" => "JE",
                "name" => "جيرسي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 114,
                "code" => "JO",
                "name" => "الأردن",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 115,
                "code" => "KZ",
                "name" => "كازاخستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 116,
                "code" => "KE",
                "name" => "كينيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 117,
                "code" => "KI",
                "name" => "كيريباتي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 118,
                "code" => "KP",
                "name" => "كوريا الشمالية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 119,
                "code" => "KR",
                "name" => "كوريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 120,
                "code" => "KW",
                "name" => "الكويت",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 121,
                "code" => "KG",
                "name" => "قيرقيزستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 122,
                "code" => "LA",
                "name" => "لاوس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 123,
                "code" => "LV",
                "name" => "لاتفيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 124,
                "code" => "LB",
                "name" => "لبنان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 125,
                "code" => "LS",
                "name" => "ليسوتو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 126,
                "code" => "LR",
                "name" => "ليبيريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 127,
                "code" => "LY",
                "name" => "ليبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 128,
                "code" => "LI",
                "name" => "لختنشتاين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 129,
                "code" => "LT",
                "name" => "ليتوانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 130,
                "code" => "LU",
                "name" => "لوكسمبورج",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 131,
                "code" => "MO",
                "name" => "ماكاو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 132,
                "code" => "MK",
                "name" => "مقدونيا، جمهورية يوغوسلافيا السابقة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 133,
                "code" => "MG",
                "name" => "مدغشقر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 134,
                "code" => "MW",
                "name" => "مالاوي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 135,
                "code" => "MY",
                "name" => "ماليزيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 136,
                "code" => "MV",
                "name" => "جزر المالديف",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 137,
                "code" => "ML",
                "name" => "مالي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 138,
                "code" => "MT",
                "name" => "مالطا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 139,
                "code" => "MH",
                "name" => "جزر مارشال",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 140,
                "code" => "MQ",
                "name" => "مارتينيك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 141,
                "code" => "MR",
                "name" => "موريتانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 142,
                "code" => "MU",
                "name" => "موريشيوس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 143,
                "code" => "YT",
                "name" => "مايوت",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 144,
                "code" => "MX",
                "name" => "المكسيك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 145,
                "code" => "FM",
                "name" => "ماكرونيزيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 146,
                "code" => "MD",
                "name" => "مولدوفا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 147,
                "code" => "MC",
                "name" => "موناكو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 148,
                "code" => "MN",
                "name" => "منغوليا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 149,
                "code" => "ME",
                "name" => "مونتينيغرو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 150,
                "code" => "MS",
                "name" => "مونتسيرات",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 151,
                "code" => "MA",
                "name" => "المغرب",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 152,
                "code" => "MZ",
                "name" => "موزمبيق",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 153,
                "code" => "MM",
                "name" => "ميانمار",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 154,
                "code" => "NA",
                "name" => "ناميبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 155,
                "code" => "NR",
                "name" => "ناورو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 156,
                "code" => "NP",
                "name" => "نيبال",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 157,
                "code" => "NL",
                "name" => "هولندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 158,
                "code" => "NC",
                "name" => "كاليدونيا الجديدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 159,
                "code" => "NZ",
                "name" => "نيوزيلندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 160,
                "code" => "NI",
                "name" => "نيكاراجوا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 161,
                "code" => "NE",
                "name" => "النيجر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 162,
                "code" => "NG",
                "name" => "نيجيريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 163,
                "code" => "NU",
                "name" => "نيوا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 164,
                "code" => "NF",
                "name" => "جزيرة نورفوك",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 165,
                "code" => "MP",
                "name" => "جزر ماريانا الشمالية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 166,
                "code" => "NO",
                "name" => "النرويج",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 167,
                "code" => "OM",
                "name" => "عمان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 168,
                "code" => "PK",
                "name" => "باكستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 169,
                "code" => "PW",
                "name" => "بالاو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 170,
                "code" => "PS",
                "name" => "السلطة الفلسطينية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 171,
                "code" => "PA",
                "name" => "بنما",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 172,
                "code" => "PG",
                "name" => "بابوا-غينيا الجديدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 173,
                "code" => "PY",
                "name" => "باراجواي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 174,
                "code" => "PE",
                "name" => "بيرو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 175,
                "code" => "PH",
                "name" => "الفلبين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 176,
                "code" => "PN",
                "name" => "جزر البتكارين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 177,
                "code" => "PL",
                "name" => "بولندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 178,
                "code" => "PT",
                "name" => "البرتغال",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 179,
                "code" => "PR",
                "name" => "بورتو ريكو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 180,
                "code" => "QA",
                "name" => "قطر",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 181,
                "code" => "RE",
                "name" => "ريونيون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 182,
                "code" => "RO",
                "name" => "رومانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 183,
                "code" => "RU",
                "name" => "روسيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 184,
                "code" => "RW",
                "name" => "رواندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 185,
                "code" => "BL",
                "name" => "سانت بارتيليمي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 186,
                "code" => "SH",
                "name" => "سانت هيلينا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 187,
                "code" => "KN",
                "name" => "سانت كيتس ونيفيس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 188,
                "code" => "LC",
                "name" => "سانت لوشيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 189,
                "code" => "MF",
                "name" => "سانت مارتن",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 190,
                "code" => "PM",
                "name" => "سانت بيير وميكولون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 191,
                "code" => "VC",
                "name" => "سانت فينسنت وجرينادينز",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 192,
                "code" => "WS",
                "name" => "ساموا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 193,
                "code" => "SM",
                "name" => "سان مارينو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 194,
                "code" => "ST",
                "name" => "ساوتوماي وبرينسيبا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 195,
                "code" => "SA",
                "name" => "المملكة العربية السعودية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 196,
                "code" => "SN",
                "name" => "السنغال",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 197,
                "code" => "RS",
                "name" => "صربيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 198,
                "code" => "SC",
                "name" => "سيشل",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 199,
                "code" => "SL",
                "name" => "سيراليون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 200,
                "code" => "SG",
                "name" => "سنغافورة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 201,
                "code" => "SX",
                "name" => "سينت مارتن",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 202,
                "code" => "SK",
                "name" => "سلوفاكيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 203,
                "code" => "SI",
                "name" => "سلوفينيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 204,
                "code" => "SB",
                "name" => "جزر سولومون",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 205,
                "code" => "SO",
                "name" => "الصومال",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 206,
                "code" => "ZA",
                "name" => "جنوب أفريقيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 207,
                "code" => "GS",
                "name" => "جورجيا الجنوبية وجزر ساندويتش الجنوبية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 208,
                "code" => "SS",
                "name" => "جنوب السودان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 209,
                "code" => "ES",
                "name" => "أسبانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 210,
                "code" => "LK",
                "name" => "سيريلانكا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 211,
                "code" => "SD",
                "name" => "السودان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 212,
                "code" => "SR",
                "name" => "سورينام",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 213,
                "code" => "SJ",
                "name" => "سفالبارد وجان ماين",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 214,
                "code" => "SZ",
                "name" => "سوازيلاند",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 215,
                "code" => "SE",
                "name" => "السويد",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 216,
                "code" => "CH",
                "name" => "سويسرا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 217,
                "code" => "SY",
                "name" => "سوريا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 218,
                "code" => "TW",
                "name" => "تايوان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 219,
                "code" => "TJ",
                "name" => "طاجيكستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 220,
                "code" => "TZ",
                "name" => "تنزانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            [
                "id" => 221,
                "code" => "TH",
                "name" => "تايلاند",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ],
            array(
                "id" => 222,
                "code" => "TL",
                "name" => "تيمور الشرقية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 223,
                "code" => "TG",
                "name" => "توجو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 224,
                "code" => "TK",
                "name" => "توكيلاو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 225,
                "code" => "TO",
                "name" => "تونجا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 226,
                "code" => "TT",
                "name" => "ترينيداد وتوباجو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 227,
                "code" => "TN",
                "name" => "تونس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 228,
                "code" => "TR",
                "name" => "تركيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 229,
                "code" => "TM",
                "name" => "تركمانستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 230,
                "code" => "TC",
                "name" => "جزر تركس وكايكوس",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 231,
                "code" => "TV",
                "name" => "توفالو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 232,
                "code" => "UG",
                "name" => "أوغندا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 233,
                "code" => "UA",
                "name" => "أوكرانيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 234,
                "code" => "AE",
                "name" => "الإمارات العربية المتحدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 235,
                "code" => "GB",
                "name" => "المملكة المتحدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 236,
                "code" => "US",
                "name" => "الولايات المتحدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 237,
                "code" => "UM",
                "name" => "جزر فرعية تابعة للولايات المتحدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 238,
                "code" => "UY",
                "name" => "أوروجواي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 239,
                "code" => "UZ",
                "name" => "أوزبكستان",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 240,
                "code" => "VU",
                "name" => "فانواتو",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 241,
                "code" => "VE",
                "name" => "فنزويلا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 242,
                "code" => "VN",
                "name" => "فيتنام",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 243,
                "code" => "VG",
                "name" => "جزر العذراء البريطانية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 244,
                "code" => "VI",
                "name" => "جزر العذراء، الولايات المتحدة",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 245,
                "code" => "WF",
                "name" => "واليس وفوتونا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 246,
                "code" => "EH",
                "name" => "الصحراء الغربية",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 247,
                "code" => "YE",
                "name" => "اليمن",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 248,
                "code" => "ZM",
                "name" => "زامبيا",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
            array(
                "id" => 249,
                "code" => "ZW",
                "name" => "زيمبابوي",
                "created_at" => NULL,
                "updated_at" => NULL,
                "deleted_at" => NULL,
            ),
        ));
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('countries');
    }
};
